module.exports = [
  {
    Company: '287 Craft Spirits',
    'Company Address - Work Street': '5846 S College Ave.',
    'Company Address - Work City': 'Fort Collins',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80525,
    'Company Web address - Work': 'http://www.287craftspirits.com',
  },
  {
    Company: '3 Forks Ranch',
    'Company Address - Work Street': '681 County Road 129',
    'Company Address - Work City': 'Slater',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81653,
    'Company Web address - Work': 'http://www.threeforksranch.com/',
  },
  {
    Company: '3S Liquors',
    'Company Address - Work Street': '8031 Wadsworth Blvd Unit A1',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80003,
    'Company Web address - Work': '',
  },
  {
    Company: '82 Liquors',
    'Company Address - Work Street': '2550 CO-82 ',
    'Company Address - Work City': 'Glenwood Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81601,
    'Company Web address - Work': 'http://82liquors.com',
  },
  {
    Company: 'Acme Liquor Store',
    'Company Address - Work Street': '510 Belleview Ave',
    'Company Address - Work City': 'Crested Butte',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81224,
    'Company Web address - Work': '',
  },
  {
    Company: 'Alpine Liquor Store',
    'Company Address - Work Street': '134 Emma Rd',
    'Company Address - Work City': 'Basalt',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81621,
    'Company Web address - Work': '',
  },
  {
    Company: "Antler's Liquor and Wine Cellar",
    'Company Address - Work Street': '842 Summit Blvd',
    'Company Address - Work City': 'Frisco',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80443,
    'Company Web address - Work': 'http://antlersliquor.com',
  },
  {
    Company: 'Applejack Wine & Spirits',
    'Company Address - Work Street': '3320 Youngfield St.',
    'Company Address - Work City': 'Wheatridge',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80033,
    'Company Web address - Work': 'https://applejack.com/',
  },
  {
    Company: 'Argonaut Wine & Liquor',
    'Company Address - Work Street': '760 E Colfax Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80203,
    'Company Web address - Work': 'http://argonautliquor.com',
  },
  {
    Company: 'Aspen Park Wine & Spirits',
    'Company Address - Work Street': '25937 Conifer Rd.',
    'Company Address - Work City': 'Conifer',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80433,
    'Company Web address - Work': 'http://www.aspenparkwineandspirits.com/',
  },
  {
    Company: 'Aspen Wine & Spirits',
    'Company Address - Work Street': '300 Puppy Smith St.',
    'Company Address - Work City': 'Aspen',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81611,
    'Company Web address - Work': 'http://aspenwineandspirit.com/',
  },
  {
    Company: 'Atlas Valley Purveyors',
    'Company Address - Work Street': '2770 Arapahoe Rd Unit 100',
    'Company Address - Work City': 'Lafayette',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80026,
    'Company Web address - Work': 'http://avpurveyors.com',
  },
  {
    Company: 'Bacchus Wine & Spirits',
    'Company Address - Work Street': '9265 S Broadway Unit 400',
    'Company Address - Work City': 'Littleton',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80129,
    'Company Web address - Work': 'http://www.bacchuswinesandspirits.com',
  },
  {
    Company: 'Base Camp Wine and Spirits',
    'Company Address - Work Street': '223 Lusher Ct Unit 1',
    'Company Address - Work City': 'Frisco',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80443,
    'Company Web address - Work': 'https://basecampliquors.com/',
  },
  {
    Company: 'Bear Valley Wine and Spirits',
    'Company Address - Work Street': '3100 S Sheridan Blvd Unit  F',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80227,
    'Company Web address - Work': 'http://bearvalleyliquor.com',
  },
  {
    Company: 'Besame Steamboat',
    'Company Address - Work Street': '818 Lincoln Avenue Box 883427',
    'Company Address - Work City': 'Steamboat Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80487,
    'Company Web address - Work': 'http://besamesteamboat.com',
  },
  {
    Company: 'Beverage Werks',
    'Company Address - Work Street': '3765, 1285 A E 1st Ave',
    'Company Address - Work City': 'Broomfield',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80020,
    'Company Web address - Work': 'http://beveragewerks.net/',
  },
  {
    Company: 'Biggie Wine & Liquor',
    'Company Address - Work Street': '5587 Conifer Rd Unit  125',
    'Company Address - Work City': 'Conifer',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80433,
    'Company Web address - Work': '',
  },
  {
    Company: 'Bird American Comfort Food (Black Pearl Restaurant)',
    'Company Address - Work Street': '1529 S. Pearl St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80210,
    'Company Web address - Work': 'http://birddenver.com',
  },
  {
    Company: "Bogey's Beer and Wine",
    'Company Address - Work Street': '3911 Fox St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80216,
    'Company Web address - Work': 'http://bogeysbeer.com',
  },
  {
    Company: 'Bottle Pass Liquors',
    'Company Address - Work Street': '35 Co Rd 804',
    'Company Address - Work City': 'Fraser',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80442,
    'Company Web address - Work': 'http://bottlepassliquors.com',
  },
  {
    Company: 'Bottle Shop 33',
    'Company Address - Work Street': '1080 S Gaylord St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80209,
    'Company Web address - Work': 'http://www.bottleshop33.com',
  },
  {
    Company: 'Boulder Wine and Spirits',
    'Company Address - Work Street': '3325 28th St Unit 3',
    'Company Address - Work City': 'Boulder',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80301,
    'Company Web address - Work': 'http://boulderwineandspirits.net',
  },
  {
    Company: 'Brix Wine and Spirits',
    'Company Address - Work Street': '6130 E Cross Roads Blvd.',
    'Company Address - Work City': 'Loveland',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80538,
    'Company Web address - Work': 'http://brixwineandspirits.com',
  },
  {
    Company: 'Bubbles Liquor Mart',
    'Company Address - Work Street': '675 Genoa Way',
    'Company Address - Work City': 'Castle Rock',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80109,
    'Company Web address - Work': 'http://bubblesliquorworld.com',
  },
  {
    Company: 'Butchers Bistro',
    'Company Address - Work Street': '2233 Larimer St',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80205,
    'Company Web address - Work': 'https://www.thebutchersbistro.com/',
  },
  {
    Company: 'C Lazy U Ranch',
    'Company Address - Work Street': '640 Colorado Hwy 125',
    'Company Address - Work City': 'Granby',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80446,
    'Company Web address - Work': 'http://www.clazyu.com',
  },
  {
    Company: 'Cask and Craft',
    'Company Address - Work Street': '3744 Tejon St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80211,
    'Company Web address - Work': 'http://www.caskandcraft.com',
  },
  {
    Company: 'Chambers Wine and Liquors',
    'Company Address - Work Street': '15260 E Iliff Ave.',
    'Company Address - Work City': 'Aurora',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80014,
    'Company Web address - Work': 'http://www.chamberswineandliquor.com',
  },
  {
    Company: 'Chatfield Wine & Spirits',
    'Company Address - Work Street': '8156 S Wadsworth Blvd.',
    'Company Address - Work City': 'Littleton',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80128,
    'Company Web address - Work': 'https://www.chatfieldwineandspirits.com/',
  },
  {
    Company: 'Cheers Liquor Mart',
    'Company Address - Work Street': '1105 N Circle Dr',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80909,
    'Company Web address - Work': 'https://www.cheersliquormart.com/',
  },
  {
    Company: 'Cherry Hills Country Club',
    'Company Address - Work Street': '4125 S University Blvd.',
    'Company Address - Work City': 'Cherry Hills Village',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80113,
    'Company Web address - Work': 'http://www.chcc.com',
  },
  {
    Company: 'Chiba Bar',
    'Company Address - Work Street': '19 E Kiowa St. ',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80903,
    'Company Web address - Work': 'http://chiba-bar.com',
  },
  {
    Company: "Chuey Fu's Baja Cantina",
    'Company Address - Work Street': '100 16th St Mall Unit 145',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80205,
    'Company Web address - Work': 'https://chueyfus.com/',
  },
  {
    Company: 'CO. Ranch House (Western Hospitality Group)',
    'Company Address - Work Street': '704 Grand Ave',
    'Company Address - Work City': 'Glenwood Dprings',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81601,
    'Company Web address - Work': '',
  },
  {
    Company: 'Coaltrain Fine Wine and Spirits',
    'Company Address - Work Street': '330 W Uintah St.',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80905,
    'Company Web address - Work': 'http://coaltrainwine.com',
  },
  {
    Company: 'Colorado Golf Club',
    'Company Address - Work Street': '8000 Preservation Trail',
    'Company Address - Work City': 'Parker',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80134,
    'Company Web address - Work': 'http://www.coloradogolfclub.com/',
  },
  {
    Company: 'Colorado Liquor Outlet',
    'Company Address - Work Street': '1615 Briargate Blvd.',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80920,
    'Company Web address - Work': '',
  },
  {
    Company: 'Cooper Wine and Spirits',
    'Company Address - Work Street': '732 Cooper Ave.',
    'Company Address - Work City': 'Glenwood Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81601,
    'Company Web address - Work': 'http://cooperwineandspirits.com',
  },
  {
    Company: 'Cottonwood Liquors',
    'Company Address - Work Street': '3645 S College Ave.',
    'Company Address - Work City': 'Fort Collins',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80525,
    'Company Web address - Work': '',
  },
  {
    Company: 'Country Club Liquors',
    'Company Address - Work Street': '939 E Cedar Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80209,
    'Company Web address - Work': '',
  },
  {
    Company: 'Craft Alley',
    'Company Address - Work Street': '1455 S Pearl St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80210,
    'Company Web address - Work': 'http://denver.craftalley.co',
  },
  {
    Company: 'Crafty Fox',
    'Company Address - Work Street': '3901 Fox St',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80216,
    'Company Web address - Work': 'https://craftyfox.beer/',
  },
  {
    Company: 'Crested Butte Nordic',
    'Company Address - Work Street': '620 2nd St',
    'Company Address - Work City': 'Cressted Butte',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81224,
    'Company Web address - Work': '',
  },
  {
    Company: "Crystal's Liquor",
    'Company Address - Work Street': '356 E Harmony Rd Unit  6C',
    'Company Address - Work City': 'Fort Collins',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80525,
    'Company Web address - Work': '',
  },
  {
    Company: "Davidson's Liquor Colorado- Highlands Ranch",
    'Company Address - Work Street': '5555 Boatworks Dr.',
    'Company Address - Work City': 'Highlands Ranch',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80126,
    'Company Web address - Work': 'https://www.davidsonsliquors.com/',
  },
  {
    Company: 'Davidsons Beer, Wine & Spirits - Centennial',
    'Company Address - Work Street':
      '15745 E Arapahoe Rd, Centennial, CO 80016',
    'Company Address - Work City': 'Centennial',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80016,
    'Company Web address - Work': 'https://www.davidsonscentennial.com',
  },
  {
    Company: 'Denver Country Club',
    'Company Address - Work Street': '1700 E 1st Ave. ',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80218,
    'Company Web address - Work': 'http://www.denvercc.net',
  },
  {
    Company: 'Denver Liquor Galaxy',
    'Company Address - Work Street': '8970 E Hampden Ave',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80231,
    'Company Web address - Work': '',
  },
  {
    Company: "Devil's Thumb Ranch",
    'Company Address - Work Street': '3530 County Rd 83',
    'Company Address - Work City': 'Tabernash',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80478,
    'Company Web address - Work': 'http://devilsthumbranch.com',
  },
  {
    Company: 'DIA Liquor Warehouse',
    'Company Address - Work Street': '4739 Yampa St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80249,
    'Company Web address - Work': '',
  },
  {
    Company: 'Downtown Fine Spirits & Wines',
    'Company Address - Work Street': '103 Wahsatch Ave.',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80903,
    'Company Web address - Work': 'http://dtnfspiritsandwines.com',
  },
  {
    Company: 'El Jebeverage',
    'Company Address - Work Street': '300 E Valley Road',
    'Company Address - Work City': 'Carbondale',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81623,
    'Company Web address - Work': '',
  },
  {
    Company: "Elway's- Cherry Creek",
    'Company Address - Work Street': '2500 E 1st Ave Unit 101',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80206,
    'Company Web address - Work': 'http://www.elways.com/',
  },
  {
    Company: 'Evergreen Discount Liquors',
    'Company Address - Work Street': '3847 Evergreen Pkwy.',
    'Company Address - Work City': 'Evergreen',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80439,
    'Company Web address - Work': 'http://evergreendiscountliquors.com',
  },
  {
    Company: 'Federal Liquors',
    'Company Address - Work Street': '3755 Federal Blvd',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80211,
    'Company Web address - Work': '',
  },
  {
    Company: "Fish's Liquor",
    'Company Address - Work Street': '1007 E Harmony Rd.',
    'Company Address - Work City': 'Fort Collins',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80525,
    'Company Web address - Work': 'http://fishsliquor.com',
  },
  {
    Company: 'Fort Collins Country Club',
    'Company Address - Work Street': '1920 Country Club Road',
    'Company Address - Work City': 'Fort Collins',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80524,
    'Company Web address - Work':
      'http://www.clubcorp.com/Clubs/Fort-Collins-Country-Club',
  },
  {
    Company: 'Fort Collins Warehouse Liquors',
    'Company Address - Work Street': '4700 E Boardwalk Dr.',
    'Company Address - Work City': 'Fort Collins',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80525,
    'Company Web address - Work': 'http://fortcollinswarehouseliquors.com',
  },
  {
    Company: 'Four Dogs Fine Wines & Spirits',
    'Company Address - Work Street': '350 Reed St Unit 218',
    'Company Address - Work City': 'Basalt',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81621,
    'Company Web address - Work': 'http://fourdogswine.com',
  },
  {
    Company: 'FREE RANGE KITCHEN & WINE BAR',
    'Company Address - Work Street': '305 Gold Rivers Ct.',
    'Company Address - Work City': 'Basalt',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81621,
    'Company Web address - Work': 'https://www.freerangebasalt.com/',
  },
  {
    Company: 'Glenmoor Country Club',
    'Company Address - Work Street': '110 Glenmoor Dr. ',
    'Company Address - Work City': 'Englewood',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80113,
    'Company Web address - Work': 'http://glenmoorcc.org',
  },
  {
    Company: 'Grand Lake Lodge',
    'Company Address - Work Street': '15500 US Highway 34',
    'Company Address - Work City': 'Grand Lake',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80447,
    'Company Web address - Work': 'http://grandlakelodge.com',
  },
  {
    Company: 'Grand Lake Wine & Spirits',
    'Company Address - Work Street': '904 Grand Ave.',
    'Company Address - Work City': 'Grand Lake',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80447,
    'Company Web address - Work': '',
  },
  {
    Company: 'Grandby Market Place Liquor',
    'Company Address - Work Street': '1131 Thompson Rd',
    'Company Address - Work City': 'Grandby',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80446,
    'Company Web address - Work': '',
  },
  {
    Company: 'Grape Expectations WIne & Spirits',
    'Company Address - Work Street': '2270 Kearney St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80207,
    'Company Web address - Work': 'http://grapeexpectationsdenver.com',
  },
  {
    Company: 'Great Vines Liquor',
    'Company Address - Work Street': '6140 S Gun Club Rd.',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80016,
    'Company Web address - Work': 'http://www.greatvinesliquors.net',
  },
  {
    Company: 'Great Western Grog Shop (Paul Robinson Inc.)',
    'Company Address - Work Street': '710 E Durant Ave.',
    'Company Address - Work City': 'Aspen',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81611,
    'Company Web address - Work': 'http://www.aspengrogshop.com',
  },
  {
    Company: "Hazel's Beverage World",
    'Company Address - Work Street': '1955 28th St.',
    'Company Address - Work City': 'Boulder',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80301,
    'Company Web address - Work': 'http://www.hazelsboulder.com',
  },
  {
    Company: 'Heritage Wine and Liquor',
    'Company Address - Work Street': '7475 E Arapahoe Rd.',
    'Company Address - Work City': 'Centennial',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80112,
    'Company Web address - Work': 'http://www.heritagewineandliquor.com',
  },
  {
    Company: 'Highlands Wine & Liquor',
    'Company Address - Work Street': '4650 W 38th Ave',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80212,
    'Company Web address - Work': 'http://highlandsliquor.com/',
  },
  {
    Company: 'Highlands Wineseller',
    'Company Address - Work Street': '670 Timberline Rd.',
    'Company Address - Work City': 'Highlands Ranch',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80130,
    'Company Web address - Work': 'http://www.highlandswineseller.com',
  },
  {
    Company: 'Hill Top Liquor (Hiwat Corp)',
    'Company Address - Work Street': '6390 Wadsworth Bypass Unit  B',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80003,
    'Company Web address - Work': '',
  },
  {
    Company: 'HJM Wine & Spirits',
    'Company Address - Work Street': '2016 W 32nd Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80211,
    'Company Web address - Work': '',
  },
  {
    Company: 'Hotel Jerome',
    'Company Address - Work Street': '30 E Main St.',
    'Company Address - Work City': 'Aspen',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81611,
    'Company Web address - Work': 'http://hoteljerome.aubergeresorts.com',
  },
  {
    Company: "Hugo's Colorado Beer & Spirits",
    'Company Address - Work Street': '205 E 13th Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80218,
    'Company Web address - Work': 'http://hugosbeer.com',
  },
  {
    Company: 'Hyatt Regency CO Convention Center (Former Saint)',
    'Company Address - Work Street': '650 15th St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80202,
    'Company Web address - Work':
      'https://www.hyatt.com/en-US/hotel/colorado/hyatt-regency-denver-at-colorado-convention-center/dencc',
  },
  {
    Company: 'J & K Liquor',
    'Company Address - Work Street': '2906 N Powers Blvd. ',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80922,
    'Company Web address - Work': 'http://jkliquor.com',
  },
  {
    Company: "Jerri's Tobacco Shop & Fine Wines",
    'Company Address - Work Street': '500 16th Unit 136',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80202,
    'Company Web address - Work': 'http://www.denvercigars.com',
  },
  {
    Company: "Jimbo's Liquor",
    'Company Address - Work Street': '128 Basalt Center Cir.',
    'Company Address - Work City': 'Basalt',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81621,
    'Company Web address - Work': '',
  },
  {
    Company: 'Joy Wine & Spirits',
    'Company Address - Work Street': '1302 E 6th Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80218,
    'Company Web address - Work': 'https://www.joywineandspirits.com/',
  },
  {
    Company: 'Kent Cellars',
    'Company Address - Work Street': '3475 S University Blvd.',
    'Company Address - Work City': 'Englewood',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80113,
    'Company Web address - Work': 'https://kent-cellars.business.site/',
  },
  {
    Company: 'Larimer Beer Hall',
    'Company Address - Work Street': '2012 Larimer St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80205,
    'Company Web address - Work': 'http://larimerbeerhall.com',
  },
  {
    Company: 'Lazy Dog Sports Bar & Grill',
    'Company Address - Work Street': '1346 Pearl St.',
    'Company Address - Work City': 'Boulder',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80302,
    'Company Web address - Work': 'https://www.thelazydog.com/',
  },
  {
    Company: 'Linger',
    'Company Address - Work Street': '2030 W 30th Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80211,
    'Company Web address - Work': 'http://lingerdenver.com',
  },
  {
    Company: 'Liquor Mart',
    'Company Address - Work Street': '750 15th St.',
    'Company Address - Work City': 'Boulder',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80302,
    'Company Web address - Work': 'http://www.liquormart.com',
  },
  {
    Company: "Little's Wine and Spirits",
    'Company Address - Work Street': '2390 S Downing St Unit  A',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80210,
    'Company Web address - Work': 'http://www.littleswine.com',
  },
  {
    Company: 'Lukas Liquors Superstore',
    'Company Address - Work Street': '8457 S Yosemite St, Lone Tree, CO 80124',
    'Company Address - Work City': 'Lone Tree',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80124,
    'Company Web address - Work':
      'https://www.lukasliquorsuperstore.com/#/home',
  },
  {
    Company: 'Mambo Italiano',
    'Company Address - Work Street': '521 Lincoln Ave.',
    'Company Address - Work City': 'Steamboat Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80487,
    'Company Web address - Work': 'http://mambos.com',
  },
  {
    Company: 'Marshall Liquors',
    'Company Address - Work Street': '5216 Marshall St.',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80002,
    'Company Web address - Work': '',
  },
  {
    Company: 'Max Gill and Grill',
    'Company Address - Work Street': '1052 S Gaylord St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80209,
    'Company Web address - Work': 'http://www.maxgillandgrill.com',
  },
  {
    Company: 'Mayfair Liquors',
    'Company Address - Work Street': '1385 Krameria Street',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80220,
    'Company Web address - Work': 'http://www.mayfairliquors.com/',
  },
  {
    Company: 'Meat & Cheese Restaurant and Farm Shop',
    'Company Address - Work Street': '319 E Hopkins Ave.',
    'Company Address - Work City': 'Aspen',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81611,
    'Company Web address - Work': 'http://meatcheese.avalancheaspen.com',
  },
  {
    Company: 'Mile High Wine Cellars',
    'Company Address - Work Street': '15400 W 64th Ave Unit E7',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80007,
    'Company Web address - Work': '',
  },
  {
    Company: 'Mission Control Liquor Station',
    'Company Address - Work Street': '3244 Navajo St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80211,
    'Company Web address - Work': 'https://www.missioncontroldenver.com/',
  },
  {
    Company: "Molly's Spirits",
    'Company Address - Work Street': '5809 W 44th Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80212,
    'Company Web address - Work': 'http://www.mollysspirits.com',
  },
  {
    Company: 'Mondo Vino',
    'Company Address - Work Street': '3601 W 32nd Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80211,
    'Company Web address - Work': 'http://www.mondovinodenver.com',
  },
  {
    Company: 'Morgans Liquors',
    'Company Address - Work Street': '1200 E Evans Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80210,
    'Company Web address - Work': 'http://www.morgansliquors.com',
  },
  {
    Company: 'New Castle Liquors',
    'Company Address - Work Street': '820 Castle Valley Blvd Unit  104',
    'Company Address - Work City': 'New Castle',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81647,
    'Company Web address - Work': 'https://www.newcastleliquors.com/',
  },
  {
    Company: 'Of Grape & Grain',
    'Company Address - Work Street': '111 S Monarch St.',
    'Company Address - Work City': 'Aspen',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81611,
    'Company Web address - Work': '',
  },
  {
    Company: 'Old Major',
    'Company Address - Work Street': '3316 Tejon St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80211,
    'Company Web address - Work': '',
  },
  {
    Company: 'Oneida Liquors',
    'Company Address - Work Street': '2259 Oneida st',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80208,
    'Company Web address - Work': 'https://oneida-liquors.business.site/',
  },
  {
    Company: 'Outback Liquors',
    'Company Address - Work Street': '113 S Elizabeth St',
    'Company Address - Work City': 'Elizabeth',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80107,
    'Company Web address - Work': '',
  },
  {
    Company: 'Palizo',
    'Company Address - Work Street': '1472 S. Pearl St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80210,
    'Company Web address - Work': 'http://palizodenver.com',
  },
  {
    Company: 'Park Avenue Wine & Spirits',
    'Company Address - Work Street': '3480 Park Ave W Unit  E',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80216,
    'Company Web address - Work': 'http://www.parkaveliquor.com',
  },
  {
    Company: 'Parker Payless Liquors',
    'Company Address - Work Street': '9749 S Parker Rd.',
    'Company Address - Work City': 'Parker',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80134,
    'Company Web address - Work': 'http://parkerpaylessliquors.com',
  },
  {
    Company: 'Patriots Liquor',
    'Company Address - Work Street': '7935 Constitution Ave. Suite 140',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80951,
    'Company Web address - Work': '',
  },
  {
    Company: 'Pearl Wine Company',
    'Company Address - Work Street': '1886 S Pearl St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80210,
    'Company Web address - Work': 'http://pearlwinecompany.com',
  },
  {
    Company: "PJ's Wine & Spirits",
    'Company Address - Work Street': '665 Frontage Rd Unit 130',
    'Company Address - Work City': 'Longmont',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80501,
    'Company Web address - Work': 'https://www.pjwinespirits.com/',
  },
  {
    Company: 'Powers Liquor Mart',
    'Company Address - Work Street': '5847 Palmer Park Blvd',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80915,
    'Company Web address - Work': 'http://powersliquormart.com/',
  },
  {
    Company: 'Primo Vino',
    'Company Address - Work Street': '5713 Olde Wadsworth Blvd.',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80002,
    'Company Web address - Work': 'http://www.primovino.net',
  },
  {
    Company: "Pringle's Fine Wine and Spirits",
    'Company Address - Work Street': '2100 W Drake Rd Unit  11',
    'Company Address - Work City': 'Fort Collins',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80526,
    'Company Web address - Work': '',
  },
  {
    Company: 'Proof Wine & Spirits (Noble Swine, LLC)',
    'Company Address - Work Street': '3360 Larimer St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80205,
    'Company Web address - Work': 'https://www.proofwinedenver.com/',
  },
  {
    Company: 'R and J Liquors',
    'Company Address - Work Street': '88 E Agate Ave.',
    'Company Address - Work City': 'Grandby',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80446,
    'Company Web address - Work': '',
  },
  {
    Company: 'Racines',
    'Company Address - Work Street': '650 Sherman St',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80203,
    'Company Web address - Work': 'http://www.racinesrestaurant.com/',
  },
  {
    Company: 'Rice Bistro & Sushi',
    'Company Address - Work Street': '5922 S Holly St.',
    'Company Address - Work City': 'Greenwood Village',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80111,
    'Company Web address - Work': 'http://ricebistrodenver.com',
  },
  {
    Company: 'RiNo Liqour',
    'Company Address - Work Street': '3083 Brighton Blvd Suite B',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80216,
    'Company Web address - Work': 'http://rinoartdistrict.org',
  },
  {
    Company: 'Rocky Mountain Moonshine Liquors',
    'Company Address - Work Street': '76827 US-40, Fraser, CO 80442',
    'Company Address - Work City': 'Fraser',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80442,
    'Company Web address - Work': '',
  },
  {
    Company: 'Root Down- Highlands',
    'Company Address - Work Street': '1600 W 33rd Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80211,
    'Company Web address - Work': 'http://www.rootdowndenver.com/',
  },
  {
    Company: 'Royal Liquor',
    'Company Address - Work Street': '7735 Wadsworth Blvd A',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80003,
    'Company Web address - Work': '',
  },
  {
    Company: 'Sartos',
    'Company Address - Work Street': '2900 W 25th Ave',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80211,
    'Company Web address - Work': 'http://sartos.com/',
  },
  {
    Company: 'School House Kitchen & Libations',
    'Company Address - Work Street': '5660 Olde Wadsworth Blvd. ',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80002,
    'Company Web address - Work': 'http://schoolhousearvada.com',
  },
  {
    Company: 'SCP Hotel',
    'Company Address - Work Street':
      '2850 S Circle Dr, Colorado Springs, CO 80906',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80906,
    'Company Web address - Work': 'https://www.scphotel.com/',
  },
  {
    Company: 'Serenity Ridge Liquors',
    'Company Address - Work Street': '25791 E Smoky Hill Rd.',
    'Company Address - Work City': 'Aurora',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80016,
    'Company Web address - Work': '',
  },
  {
    Company: 'Ski Town Wine & Spirits',
    'Company Address - Work Street': '2300 Mt Werner Cir.',
    'Company Address - Work City': 'Steamboat Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80487,
    'Company Web address - Work': 'http://skitownws.com',
  },
  {
    Company: "Sloan's Bar & Grill",
    'Company Address - Work Street': '5850 W 25th Ave.',
    'Company Address - Work City': 'Edgewater',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80214,
    'Company Web address - Work': 'http://sloansbarandgrill.com',
  },
  {
    Company: 'Smok Barbecue',
    'Company Address - Work Street': '3330 Brighton Blvd Unit 202',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80216,
    'Company Web address - Work': '',
  },
  {
    Company: 'Sobo Liquors',
    'Company Address - Work Street': '2035 S Broadway',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80210,
    'Company Web address - Work': '',
  },
  {
    Company: 'Society Sports & Spirits',
    'Company Address - Work Street': '1434 Blake St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80202,
    'Company Web address - Work': 'http://societydenver.com',
  },
  {
    Company: 'Sopris Liquor & Wine',
    'Company Address - Work Street': '1026 CO-133',
    'Company Address - Work City': 'Carbondale',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81623,
    'Company Web address - Work': 'https://www.soprisliquor.com/',
  },
  {
    Company: 'Southside Pizzeria',
    'Company Address - Work Street': '7403 W Chatfield Ave.',
    'Company Address - Work City': 'Littleton',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80128,
    'Company Web address - Work': 'http://www.eatsouthside.com',
  },
  {
    Company: 'Spikes Liqour at Simms landing (east Vail Liqour)',
    'Company Address - Work Street': '3971 Big Horn Rd',
    'Company Address - Work City': 'Vail',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81657,
    'Company Web address - Work': '',
  },
  {
    Company: 'Springs Orleans',
    'Company Address - Work Street': '123 E Pikes Peak Ave',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80903,
    'Company Web address - Work': 'http://www.springsorleans.com',
  },
  {
    Company: 'Stroh Ranch Liquors',
    'Company Address - Work Street': '2939 S Parker Rd.',
    'Company Address - Work City': 'Parker',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80134,
    'Company Web address - Work': 'http://strohranchliquor.com',
  },
  {
    Company: 'Super Market Liquors',
    'Company Address - Work Street': '1300 E Mulberry St',
    'Company Address - Work City': 'Fort Collins',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80524,
    'Company Web address - Work': 'http://www.sml-uncorked.com/',
  },
  {
    Company: "Teller's Taproom & Kitchen",
    'Company Address - Work Street': '1990 Youngfield St.',
    'Company Address - Work City': 'Lakewood',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80215,
    'Company Web address - Work': '',
  },
  {
    Company: 'The Barley Tap and Tavern',
    'Company Address - Work Street': '635 Lincoln Ave.',
    'Company Address - Work City': 'Steamboat Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80487,
    'Company Web address - Work': 'http://www.thebarleycolorado.com/',
  },
  {
    Company: 'The Bluegrass Coffee & Bourbon Lounge',
    'Company Address - Work Street': '7415 Grandview Ave',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80002,
    'Company Web address - Work': 'https://www.thebluegrasslounge.com/',
  },
  {
    Company: 'The Red Onion',
    'Company Address - Work Street': '420 E Cooper Ave.',
    'Company Address - Work City': 'Aspen',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81611,
    'Company Web address - Work': 'http://redonionaspen.com',
  },
  {
    Company: 'The St. Regis Aspen Resort',
    'Company Address - Work Street': '315 E Dean St',
    'Company Address - Work City': 'Aspen',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81611,
    'Company Web address - Work':
      'https://www.marriott.com/hotels/travel/asexr-the-st-regis-aspen-resort/?scid=bb1a189a-fec3-4d19-a255-54ba596febe2',
  },
  {
    Company: 'The White Whale Room',
    'Company Address - Work Street': '415 S Cherokee St Unit 125',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80223,
    'Company Web address - Work': 'https://www.chasethewhitewhale.com/',
  },
  {
    Company: 'The Wine Gallery',
    'Company Address - Work Street':
      '5903 Delmonico Dr, Colorado Springs, CO 80919',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80919,
    'Company Web address - Work': 'https://www.thewinegalleryco.com/',
  },
  {
    Company: 'The Wine House',
    'Company Address - Work Street': '301 6th St,',
    'Company Address - Work City': ' Crested Butte',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81224,
    'Company Web address - Work': '',
  },
  {
    Company: 'The Woods',
    'Company Address - Work Street': '3330 Brighton Blvd',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80216,
    'Company Web address - Work': 'https://thesourcehotel.com/the-woods',
  },
  {
    Company: 'To The Wind Bistro',
    'Company Address - Work Street': '3333 E Colfax Ave, Denver, CO 80206',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80206,
    'Company Web address - Work': 'http://tothewindbistro.com/',
  },
  {
    Company: 'Tommyknocker Brewery',
    'Company Address - Work Street': '1401 Miner St.',
    'Company Address - Work City': 'Idaho Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80452,
    'Company Web address - Work': 'http://tommyknocker.com',
  },
  {
    Company: 'Total Beverage- Thorton',
    'Company Address - Work Street': '900 E 104th Ave',
    'Company Address - Work City': 'Thorton',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80233,
    'Company Web address - Work': '',
  },
  {
    Company: 'Total Wine & Liquor',
    'Company Address - Work Street': '2713 Janitell Rd',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80920,
    'Company Web address - Work': 'http://totalwineandliquor.com',
  },
  {
    Company: 'Total Wine and More',
    'Company Address - Work Street': '3905 E Evans Ave.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80210,
    'Company Web address - Work': 'http://www.totalwine.com/denver',
  },
  {
    Company: 'Treasury Liquors',
    'Company Address - Work Street': '611 Gothic Rd',
    'Company Address - Work City': 'Crested Butte',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 81224,
    'Company Web address - Work': '',
  },
  {
    Company: 'Union Wine & Spirits',
    'Company Address - Work Street': '295 S Union Blvd',
    'Company Address - Work City': 'Lakewood',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80228,
    'Company Web address - Work': 'http://unionwinespirits.placeweb.site/',
  },
  {
    Company: 'Vertical Bistro & Tap',
    'Company Address - Work Street': '130 Parry Peak Way',
    'Company Address - Work City': 'Winter Park',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80482,
    'Company Web address - Work': 'http://verticalbistro.com',
  },
  {
    Company: 'Veterans Wine & Liquor',
    'Company Address - Work Street': '3630 Austin Bluffs Pkwy Unit 170',
    'Company Address - Work City': 'Colorado Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80918,
    'Company Web address - Work': '',
  },
  {
    Company: 'Vineland Liquors',
    'Company Address - Work Street': '8770 Wadsworth Blvd Unit  K',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80003,
    'Company Web address - Work': '',
  },
  {
    Company: 'Virginia Village Liquor',
    'Company Address - Work Street': '1455 S Holly St.',
    'Company Address - Work City': 'Denver',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80222,
    'Company Web address - Work': '',
  },
  {
    Company: 'Water Tower Liquors',
    'Company Address - Work Street': '5545 Olde Wadsworth Blvd.',
    'Company Address - Work City': 'Arvada',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80002,
    'Company Web address - Work': '',
  },
  {
    Company: "Wilbur's Total Beverage",
    'Company Address - Work Street': '2201 S College Ave.',
    'Company Address - Work City': 'Fort Collins',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80525,
    'Company Web address - Work': 'http://www.wilburstotalbeverage.com',
  },
  {
    Company: 'Wild Plum',
    'Company Address - Work Street': '2525 Village Dr.',
    'Company Address - Work City': 'Steamboat Springs',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80487,
    'Company Web address - Work': '',
  },
  {
    Company: 'Willow Creek Wine & Spirits (Mojo Beau Co)',
    'Company Address - Work Street': '8200 S Quebec St a2',
    'Company Address - Work City': 'Centennial',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80112,
    'Company Web address - Work': '',
  },
  {
    Company: 'Winter Park Wine and Spirits',
    'Company Address - Work Street': '78911 US-40',
    'Company Address - Work City': 'Winter Park',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80482,
    'Company Web address - Work': '',
  },
  {
    Company: "Ya Ya's Euro Bistro (PB&J Restaurants, Inc.)",
    'Company Address - Work Street': '8310 E Belleview Ave',
    'Company Address - Work City': 'Greenwood Village',
    'Company Address - Work State': 'CO',
    'Company Address - Work Zip': 80111,
    'Company Web address - Work': 'http://www.yayasdenver.com',
  },
]
