const styles = {
	card: {
		maxWidth: 275,
		maxHeight: 90,
		minHeight: 90,
		// Top: 0,
		// left: 0,
		// right: 'auto',
		width: '100%',
		display: 'flex',
		zIndex: 1100,
		borderRadius: 'unset',
		boxSizing: 'border-box',
		boxShadow: 'unset',
		flexShrink: 0,
		flexDirection: 'column',
		position: 'fixed',
		backgroundPosition: 'center center',
		backgroundSize: 'cover',
		// BackgroundImage: `url(/leftCorner.png)`,
		background: `#D6D1C4`,
		boxShadow: `0px 2px 4px -1px rgba(0, 0, 0, 0.2), 
    0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12)`,
	},
}
