backend:
  name: git-gateway
  branch: master
media_folder: static/images/uploads
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields: 
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields: 
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}
  - name: "recipes"
    label: "Recipes"
    files:
    - label: "Recipes"
      name: "Recipes"
      file: "content/recipes/index.md"
      fields: 
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Recipes'
          name: "recipes"
          widget: list
          fields: 
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "markdown"} 
            - { label: "Ingredients", name: "ingredients", widget: "markdown"} 
            - { label: "Preparation", name: "ingredients", widget: "markdown"}                