backend:
  name: git-gateway
  branch: staging
media_folder: public/images/uploads
collections:
  - label: "Recipes"
    name: "recipes"
    folder: "content/recipes"
    create: true
    label_singular: "Recipe"
    fields: [
      {label: "Type", type: "layout", widget: "hidden", default: "recipe"},
      { label: "Image", name: "image", widget: "image" },
      { label: "Title", name: "title", widget: "string" },
      { label: "Description", name: "description", widget: "text", required: false },
      { label: "Ingredients", name: "ingredients", widget: "text" },
      { label: "Preparation", name: "preparation", widget: "text" },
      { label: "Tags", name: "tags", widget: "list" },
      {
          label: "Season",
          name: "season",
          widget: "select",
          options: ["Winter", "Spring", "Summer", "Fall"],
        },
      {
          label: "Source",
          name: "source",
          widget: "object",
          required: false,
          fields:
            [
              { label: "name", name: "name", widget: "text" , default: "Locke + Co"},
              { label: "url", name: "url", widget: "text" , default: "https://lockeandcodistilling.com"},
              { label: "note", name: "note", widget: "text", default: "in house"},
            ],
        }]    
  - label: "Summer Recipes"
    name: "summer_recipes"
    folder: "content/recipes"
    create: true
    filter: {field: "season", value: "Summer"}
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - label: "All Recipes"
    name: "all_recipes"
    folder: "content/recipes"
    create: true
    filter: {field: "type", value: "recipe"}
    fields:
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
          
   