backend:
  name: test-repo
  branch: staging
media_folder: public/images/uploads
collections:
    - label: "Recipes"
      name: "Recipes"
      folder: "content/recipes"
      create: true
      label_singular: "Recipe"
      fields: 
            - { label: "Title", name: "title", widget: "string"}
            - { label: "Description", name: "description", widget: "markdown"} 
            - { label: "Ingredients", name: "ingredients", widget: "markdown"} 
            - { label: "Preparation", name: "preparation", widget: "markdown"}      

          