backend:
  name: git-gateway
  branch: staging
media_folder: public/images/uploads
collections:
  - label: "Recipes"
    name: "Recipes"
    file: "content/recipes.md"
    create: true
    label_singular: "Recipe"
    fields: [
      { label: "Image", name: "image", widget: "image" },
      { label: "Title", name: "title", widget: "string" },
      { label: "Description", name: "description", widget: "markdown", required: false },
      { label: "Ingredients", name: "ingredients", widget: "markdown" },
      { label: "Preparation", name: "preparation", widget: "markdown" },
      { label: "Tags", name: "tags", widget: "list" },
      {
          label: "Season",
          name: "season",
          widget: "select",
          options: ["Winter", "Spring", "Summer", "Fall"],
        },
      {
          label: "Source",
          name: "source",
          widget: "object",
          required: false,
          fields:
            [
              { label: "name", name: "name", widget: "text" , default: "Locke + Co"},
              { label: "url", name: "url", widget: "text" , default: "https://lockeandcodistilling.com"},
              { label: "note", name: "note", widget: "text", default: "in house"},
            ],
        }]
  - {label: "Location", name: "location", widget: "map" }                
